### ISSUE TITLE
Unattended "npm init playwright@next -- --ct" fails: The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by marcindulak** [microsoft/create-playwright#31]
When component testing argument `--ct` is specified (see https://playwright.dev/docs/test-components#how-to-get-started), with `create-playwright@next` (1.18.0-alpha-1638379596000) the following fails, but succeeds with `create-playwright@latest` (1.17.116)

```sh
npm install create-react-app
npx create-react-app playwright-components-react

cd playwright-components-react
npm install --save-dev playwright@next @playwright/experimental-ct-react@next create-playwright@next
TEST_OPTIONS='{"language":"JavaScript","framework":"react","installPlaywrightDependencies":"true"}' npm init playwright@next -- --ct
cat package.json
...
Getting started with writing end-to-end tests with Playwright:
Initializing project in '--ct'
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:372:5)
    at validateString (node:internal/validators:120:11)
    at Object.join (node:path:1172:7)
    at Generator._identifyChanges (/playwright-components-react/node_modules/create-playwright/lib/index.js:1:83384)
    at Generator.run (/playwright-components-react/node_modules/create-playwright/lib/index.js:1:81655)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /playwright-components-react/node_modules/create-playwright/lib/index.js:1:86459 {
  code: 'ERR_INVALID_ARG_TYPE'
}
```
As a consequence package.json is missing `"test-ct": "playwright test -c playwright-ct.config.js"`
```json
{
  "name": "playwright-components-react",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@testing-library/jest-dom": "^5.16.4",
    "@testing-library/react": "^13.3.0",
    "@testing-library/user-event": "^13.5.0",
    "react": "^18.1.0",
    "react-dom": "^18.1.0",
    "react-scripts": "5.0.1",
    "web-vitals": "^2.1.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "@playwright/experimental-ct-react": "^1.23.0-alpha-jun-11-2022",
    "create-playwright": "^1.18.0-alpha-1638379596000",
    "playwright": "^1.23.0-alpha-jun-11-2022"
  }
}
```

To reproduce, run (tested on Ubuntu) `DOCKER_BUILDKIT=1 docker build -t playwright . --progress=plain --no-cache`

```Dockerfile
# syntax=docker/dockerfile-upstream:1-labs
FROM node:16.15.0-bullseye-slim

# Usage
# https://github.com/moby/moby/issues/16058#issuecomment-881901519
# 1. DOCKER_BUILDKIT=1 docker build -t playwright . --progress=plain --no-cache
# 2. docker run --rm -it --name playwright playwright:latest bash

# Install playwrigth deps https://github.com/microsoft/playwright/issues/3167#issuecomment-1088152322
RUN <<-EORUN
cat <<'EOF' > /tmp/playwright-install-deps.sh
apt-get update
apt-get install -y wget

packages=(
"http://archive.ubuntu.com/ubuntu/pool/main/libj/libjpeg-turbo/libjpeg-turbo8_2.0.3-0ubuntu1_amd64.deb"
"http://archive.ubuntu.com/ubuntu/pool/main/i/icu/libicu66_66.1-2ubuntu2_amd64.deb"
"http://ftp.de.debian.org/debian/pool/main/e/enchant/libenchant1c2a_1.6.0-11.1+b1_amd64.deb"
"http://ftp.de.debian.org/debian/pool/non-free/f/fonts-ubuntu/fonts-ubuntu_0.83-4_all.deb"
"http://ftp.de.debian.org/debian/pool/non-free/f/fonts-ubuntu/ttf-ubuntu-font-family_0.83-4_all.deb"
)

for package in ${packages[@]}; do
  wget -O /tmp/$(basename $package) $package
  apt-get install -fy /tmp/$(basename $package)
done

rm -rf /tmp/*deb
rm -rf /var/lib/apt/lists/*
EOF
EORUN

RUN bash /tmp/playwright-install-deps.sh

RUN <<-EORUN
npm install create-react-app
npx create-react-app playwright-components-react
EORUN

RUN <<-EORUN
cd playwright-components-react
npm install --save-dev playwright@next @playwright/experimental-ct-react@next create-playwright@next
cat package.json
TEST_OPTIONS='{"language":"JavaScript","framework":"react","installPlaywrightDependencies":"true"}' npm init playwright@next -- --ct
cat package.json
EORUN
```

**Comment by mxschmitt** [comment]
This is expected. The next channel on NPM is not in use currently and outdated @latest will work.
